
        fcb   $34
        fcb   $7F
        fcb   $1F
        fcb   $50
        fcb   $1F
        fcb   $8B
        fcb   $31
        fcb   $8D
        fcb   $00
        fcb   $A9
        fcb   $5F
        fcb   $D7
        fcb   $8D
        fcb   $4F
        fcb   $34
        fcb   $06
        fcb   $C5
        fcb   $0F
        fcb   $26
        fcb   $03
        fcb   $8E
        fcb   $00
        fcb   $01
        fcb   $C6
        fcb   $04
        fcb   $8D
        fcb   $6D
        fcb   $E7
        fcb   $A0
        fcb   $53
        fcb   $69
        fcb   $E4
        fcb   $49
        fcb   $5C
        fcb   $2B
        fcb   $FA
        fcb   $E6
        fcb   $E4
        fcb   $AF
        fcb   $A1
        fcb   $30
        fcb   $8B
        fcb   $35
        fcb   $06
        fcb   $5C
        fcb   $C1
        fcb   $34
        fcb   $26
        fcb   $DC
        fcb   $10
        fcb   $AE
        fcb   $66
        fcb   $C6
        fcb   $01
        fcb   $8D
        fcb   $50
        fcb   $26
        fcb   $15
        fcb   $D7
        fcb   $45
        fcb   $8C
        fcb   $0C
        fcb   $45
        fcb   $5C
        fcb   $8D
        fcb   $46
        fcb   $27
        fcb   $F9
        fcb   $C6
        fcb   $00
        fcb   $C1
        fcb   $10
        fcb   $27
        fcb   $37
        fcb   $25
        fcb   $0F
        fcb   $5A
        fcb   $8D
        fcb   $39
        fcb   $1F
        fcb   $01
        fcb   $A6
        fcb   $C2
        fcb   $A7
        fcb   $A2
        fcb   $30
        fcb   $1F
        fcb   $26
        fcb   $F8
        fcb   $20
        fcb   $D9
        fcb   $8D
        fcb   $44
        fcb   $34
        fcb   $06
        fcb   $30
        fcb   $8C
        fcb   $4B
        fcb   $10
        fcb   $83
        fcb   $00
        fcb   $03
        fcb   $24
        fcb   $01
        fcb   $3A
        fcb   $8D
        fcb   $1B
        fcb   $EB
        fcb   $03
        fcb   $8D
        fcb   $32
        fcb   $DD
        fcb   $77
        fcb   $35
        fcb   $10
        fcb   $31
        fcb   $3F
        fcb   $A6
        fcb   $A9
        fcb   $12
        fcb   $34
        fcb   $A7
        fcb   $A4
        fcb   $30
        fcb   $1F
        fcb   $26
        fcb   $F4
        fcb   $20
        fcb   $B3
        fcb   $10
        fcb   $AF
        fcb   $66
        fcb   $35
        fcb   $FF
        fcb   $E6
        fcb   $84
        fcb   $6F
        fcb   $E2
        fcb   $6F
        fcb   $E2
        fcb   $86
        fcb   $12
        fcb   $20
        fcb   $09
        fcb   $A6
        fcb   $C2
        fcb   $46
        fcb   $27
        fcb   $FB
        fcb   $69
        fcb   $61
        fcb   $69
        fcb   $E4
        fcb   $5A
        fcb   $2A
        fcb   $F6
        fcb   $97
        fcb   $8D
        fcb   $EC
        fcb   $E1
        fcb   $39
        fcb   $30
        fcb   $8D
        fcb   $00
        fcb   $0E
        fcb   $3A
        fcb   $58
        fcb   $3A
        fcb   $8D
        fcb   $DC
        fcb   $E3
        fcb   $01
        fcb   $39
        fcb   $04
        fcb   $02
        fcb   $04
        fcb   $10
        fcb   $30
        fcb   $20
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $CE
        fcb   $41
        fcb   $C0
        fcb   $34
        fcb   $40
        fcb   $86
        fcb   $60
        fcb   $1F
        fcb   $8B
        fcb   $E6
        fcb   $C0
        fcb   $1D
        fcb   $84
        fcb   $01
        fcb   $C4
        fcb   $80
        fcb   $97
        fcb   $49
        fcb   $86
        fcb   $00
        fcb   $DD
        fcb   $4A
        fcb   $C6
        fcb   $00
        fcb   $DD
        fcb   $4F
        fcb   $EC
        fcb   $C1
        fcb   $2A
        fcb   $07
        fcb   $10
        fcb   $FE
        fcb   $9F
        fcb   $FF
        fcb   $7E
        fcb   $61
        fcb   $00
        fcb   $97
        fcb   $4C
        fcb   $F7
        fcb   $41
        fcb   $9E
        fcb   $37
        fcb   $26
        fcb   $B7
        fcb   $41
        fcb   $A4
        fcb   $F7
        fcb   $41
        fcb   $A7
        fcb   $34
        fcb   $40
        fcb   $86
        fcb   $02
        fcb   $97
        fcb   $48
        fcb   $BD
        fcb   $E8
        fcb   $2A
        fcb   $0C
        fcb   $4C
        fcb   $96
        fcb   $4C
        fcb   $81
        fcb   $10
        fcb   $23
        fcb   $06
        fcb   $86
        fcb   $01
        fcb   $97
        fcb   $4C
        fcb   $0C
        fcb   $4B
        fcb   $0C
        fcb   $4F
        fcb   $DE
        fcb   $4F
        fcb   $11
        fcb   $83
        fcb   $00
        fcb   $00
        fcb   $23
        fcb   $E5
        fcb   $33
        fcb   $C9
        fcb   $FF
        fcb   $00
        fcb   $86
        fcb   $00
        fcb   $B7
        fcb   $E7
        fcb   $E5
        fcb   $BD
        fcb   $40
        fcb   $00
        fcb   $35
        fcb   $40
        fcb   $20
        fcb   $A2
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00
        fcb   $00