* Generated Code

        fcb   3
Ani_smallStar *@globals
        fdb   Img_star_2
        fdb   Img_star_1
        fcb   _resetAnim
        fcb   1
Ani_largeStar *@globals
        fdb   Img_star_1
        fdb   Img_star_2
        fdb   Img_star_3
        fdb   Img_star_2
        fdb   Img_star_1
        fcb   _nextSubRoutine
        fcb   1
Ani_tails *@globals
        fdb   Img_tails_1
        fdb   Img_tails_2
        fdb   Img_tails_3
        fdb   Img_tails_4
        fdb   Img_tails_5
        fcb   _nextSubRoutine
        fcb   1
Ani_sonic *@globals
        fdb   Img_sonic_1
        fdb   Img_sonic_2
        fdb   Img_sonic_3
        fdb   Img_sonic_4
        fcb   _nextSubRoutine